### PR TITLE
feat: update libphonenumber to latest tag v8.13.50 to address the change of Benin phone number digits from 8-digits to 10-digits

### PR DESCRIPTION
**Pull request by Silas-seal**
- Benin Country Phone Numbers Are Changing From 8-digit to 10-digit Effective 30th-November-2024

### CODE REVIEW

**Comment by Silas-seal** [comment]
@jackocnr Please review and let me know if it makes sense. We need this feature in our Application by December. Thank you.

**Comment by jackocnr** [comment]
Hi there, thanks for putting this together. I'm confused as the commit says it updates LPN to the latest version of v8.9.9 whereas [the latest version](https://github.com/google/libphonenumber/releases) actually appears to be v8.13.50

**Comment by jackocnr** [comment]
Ok great. Would you be able to compress your work into a single commit? I need to keep the commit history clean.

**Comment by Silas-seal** [comment]
Sounds good. I have rebased the 2 commits it into a single commit.

**Comment by jackocnr** [comment]
Thanks for doing that. One last thing I've noticed: I don't understand why there are so many changes in the third_party/libphonenumber directory. When I look at [the history of commits to the utils file](https://github.com/jackocnr/intl-tel-input/commits/master/build/js/utils.js) (e.g. every time we update libphonenumber), they all just update the commit hash but don't actually contain any file changes in that submodule.

**Comment by Silas-seal** [comment]
Hey @jackocnr , It is weird, I have tried doing the procedures again. And actually I can't see those changes locally. I only see this. 

Screenshot 2024-11-28 at 15 58 59

Though, they don't seem to be in this repo, but strange considering the previous commits on LPN updates. Not sure, maybe I may need a hand to check that.

**Comment by jackocnr** [comment]
Thanks so much for your time on this. I'm not sure about that problem, so I implemented the update myself. Released in v24.8.0.

**Comment by Silas-seal** [comment]
Okay, Cool. Thanks for taking care of that.

**Pull request closed without merging**
