### PR TITLE
chore(intl-tel-input.ts): add @vite-ignore comment

### PR DESCRIPTION
**Pull request by mihai-ro**
Changes
* chore(intl-tel-input.ts): add @vite-ignore comment to webpackIgnore directive to ensure Vite ignores the path during bundling

### CODE REVIEW

**Comment by jackocnr** [comment]
Thanks for this, could you run `npm run build:js` to build the JS files and commit those too? (See contributing guide for more info)

**Comment by mihai-ro** [comment]
> Thanks for this, could you run `npm run build:js` to build the JS files and commit those too? (See contributing guide for more info)

Jack, I absolutely can and just did :) thank you for your hard work! is there anything else that I could help with?

**Comment by jackocnr** [comment]
Excellent, thanks. I'll do a new release in the morning.

**Comment by jackocnr** [comment]
That's released in v23.7.4.

> is there anything else that I could help with?

That's so kind of you to offer! One thing that would be really helpful, if you have time, is to help with the [test migration](https://github.com/jackocnr/intl-tel-input/issues/1630). Even if it was just moving over one or two tests that would be helpful! For example, translating the existing Jasmine test file `/src/spec/tests/options/allowDropdown.js` to the new Jest test file `/test/options/allowDropdown.test.js` (checking the other Jest tests for examples of how to do things)

**Pull request merged**
