### PR TITLE
allCountries copied to the separate data.js and data.min.js build

### PR DESCRIPTION
**Pull request by Kasheftin**
Build appended with data.js and data.min.js files that contain allCountries array only.

### CODE REVIEW

**Comment by jackocnr** [comment]
Hi there. Can you tell me why you have done this?

**Comment by Kasheftin** [comment]
Hi. I use data.js in my own implementation of telephone-input based on vuetify and libphonenumber-js. The last does not have country names. I need to show country flag selector, and the data from intl-tel-input works just fine for that. Previously I just copied the content of that file, but it seems to be a more true-way to load it with npm. Here I wrote about it, https://github.com/jackocnr/intl-tel-input/issues/1024.

**Comment by jackocnr** [comment]
Hmm fair enough. I don't see any reason to not do this 🤷‍♂ 

But I don't think we need to use the grunt replace task in this case - I don't think anything will get replaced. So if you could remove that stuff, then I think I'm happy to merge.

Thanks.

**Comment by Kasheftin** [comment]
That is strange. I can not find the reason why the tests were failed on node8. utils.js triggered an error. My update was so minor I don't believe it breaks anything.

**Comment by Kasheftin** [comment]
Is it possible to rerun these tests?

**Pull request merged**
