### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by anthony0030**
This commit:

1. Improves code comments
2. Fixes broken tests
3. Enables Dependabot
4. Improves CSS efficiency
5. Linting
6. VS Code configuration

### CODE REVIEW

**Comment by jackocnr** [comment]
Another fantastic PR, thank you.

Some feedback:
- In the readme you've changed UK English spelling to US English spelling in several places (e.g. specialised to specialized) which I'm not a fan of 😂. Unless there's a very strong advantage to be had from making this change(?), I'd rather keep it British! 🇬🇧  (plus the code is written in UK English)
- In the readme (and the react readme), it looks like you've trimmed all trailing whitespace, which when done in the code is normally a good idea, but in a markdown file can impact the layout/formatting, as that trailing double space is used to signify a line break. e.g. if you look at the Initialisation Options section, each option used to have line breaks between title, types, and description, and now they're all shoved together on the same line and I think it's less readable. Can we re-add these?
- What's the deal with adding an asterisk at the beginning of all comments e.g. "// comment" to "//* comment"? I wondered if it was a json file formatting thing, but then I saw it in the JS files too?
- I see you've updated the versions of google-closure-compiler and google-closure-library - have you tested that the "build:utils" npm script still works? I was having problems with this for ages, and in the end could only get it working with those specific versions.
- Would you be able to rebase on top of master, to get rid of that merge commit?

**Comment by anthony0030** [comment]
Hi @jackocnr, thanks for the feedback.

My answers
- The UK to US English was done by my code editor, I write US English at work and have dislexcia, I will fix this and add the settings so this never happens again, Sorry 😅.
- this is going to sound like an excuse, it was my code editor, I will fix it.
- The purpose of the asterisk in the comments differentiates commented out code from code hints, If you use a plugin like better comments for vs code.
- I ran the build script, I will check the util script manually by it self again, I found a test suite that wasn’t running and fixed it to bee 110% confident in the update, BUT I will check again.
- The merge commit happened when I did a rebase because there were conflicts, I will do my best to get it removed. Any tips would be greatly appreciated.

I will make these changes on Monday when I am back at the office.
The weekend I spend with my wife, daughter and son.

If you are ever on Thassos, let me know so we can grab beers 🍻.

**Comment by jackocnr** [comment]
That all sounds great, thanks.

> The merge commit happened when I did a rebase because there were conflicts, I will do my best to get it removed. Any tips would be greatly appreciated.

Hmm this is a big subject! But basically, in your git repo, you'll have a remote for my repo, e.g. called something like jackocnr (check the name with `git remote`), and you should be able to do `git fetch jackocnr` to get the latest changes (you can check this has worked by viewing the latest commits with `git log jackocnr/master`), and then do `git rebase jackocnr/master` to start the rebase, which means re-applying all of your commits on top of my latest changes, and then you'll probably have some conflicts (it should list which files have conflicts in the terminal) and you have to go into those files and resolve the conflicts, and then save and `git add [FILE]` for all conflicted files, and then `git rebase --continue` to keep applying your commits, and maybe you hit more conflicts and have to repeat the process, until it successfully applies all of your commits, and then you do `git push --force` to force update your remote branch (which I believe will auto update this PR), and we should be good to go 👍  If you get stuck, just let me know and I can try to do it on my end instead.

> I will make these changes on Monday when I am back at the office. The weekend I spend with my wife, daughter and son.

Lovely, enjoy! No rush from my end.

> If you are ever on Thassos, let me know so we can grab beers 🍻

No way, what a beautiful place to live!

**Comment by anthony0030** [comment]
Hi @jackocnr, thanks for the help with the rebase.

The part that I was missing was that I needed to force a push, I am using Git Tower as a GUI, and It was automatically making the merge when I did a sync.

What I did in regards to:
- UK to US changes 
  - Undid the UK to US spelling changes
  - Set the language in the config
  - Added a linter to catch future mistakes
 - The trailing spaces
   - I put a setting in vs code to stop the empty spaces from being removed
   - Added the white space back
- building the util
  - Tested it builds correctly
- Rebasing on master
  - forced a push


I also cleaned up a reminant that I forgot about and optimized when the metadata SCSS file gets made.


Is there a reason for using grunt over a different system, like gulp or esbuild?


Please let me know if any other changes are needed for this PR.

**Comment by jackocnr** [comment]
> thanks for the help with the rebase

👍 

> Is there a reason for using grunt over a different system, like gulp or esbuild?

Just because this project is 10 years old! And you know the saying: if it ain't broke...

I think of Gulp as being similarly out of date these days, no? And Esbuild is great, but my understanding is that it's just a JS bundler, rather than a generic task runner - e.g. I don't think it can be used to automate various tasks like generating responsive images, or bumping version numbers etc?

> Please let me know if any other changes are needed for this PR

Before I merge, just for a sanity check, can you briefly describe what exactly is the advantage of this change to the CSS build system - why is it more efficient? Thanks.

**Comment by anthony0030** [comment]
The advantage of the css change is that the build file is smaller with no repetition of the properties and it continues the theme of using css vars.

**Comment by jackocnr** [comment]
I've manually merged your commits, as I had to rebase again (and I changed the "Adds Whitespace back" commit to a fixup, and tweaked the "update build" commit to drop the image changes, and dropped the last 2 commits which seemed to negate each other). Thanks so much for this work! And if you have any input on moving away from Grunt, that would be very welcome!

Thanks again Anthony 💐

**Comment by jackocnr** [comment]
@anthony0030 oh dang, after I merged those commits, Travis started failing. First I tried reverting the changes in "Fixes Travis config" commit, but that still failed, so in the travis config file I took the node version from 20 back down to 16, and now it's passing again. Any thoughts?

**Comment by anthony0030** [comment]
I had the same problem, but fixed it. I think it is the cache in Travis, or an updated lock file, or a miss configuration on Travis Linux version.


Steps to try.
1. Confirm that Travis is using an up to date version of Linux ex. jammy, this is important.
2. Check that the NPM lock file is up to date
3. please let me know if the error you got


I see that you removed the test script also.

**Comment by jackocnr** [comment]
Thanks for the advice. In the end it was just a caching problem - I deleted the caches and it worked fine, so I've reverted the reverts! Thanks again.

**Comment by anthony0030** [comment]
You are very welcome!

Thanks for all your time helping me improve!

You are very appreciated, developers in open source need to know that.

**Pull request closed without merging**
