### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by mpospelov**
Fix type and put the example with formatting argument.

### CODE REVIEW

**Comment by jackocnr** [comment]
Thank you for this. I've actually just simplified the logic around setNumber, so now you actually don't have to pass a format enum - instead it automatically will format the number according to the nationalMode and separateDialCode options.

I'm interested in feedback tho - will this change work for your use case?

**Comment by mpospelov** [comment]
I think no. I caught a bug in my application, I use angular directive https://github.com/mareczek/international-phone-number and for my case I have to store 2 values one in international format(ng-model) and one the original input value. The international format value can be changed from outside of directive and it cause the original input value to change the format. To prevent this issue before changing I'm checking the current format and use this `setNumber` method. I think for my special case it won't work so I have explicitly pass the format.

**Comment by jackocnr** [comment]
I'm sorry I don't understand. Please can you explain in more detail, and with an example?

**Comment by jackocnr** [comment]
Closing due to inactivity.

**Pull request closed without merging**
