### PR TITLE
Feature: autoComplete=polite

### PR DESCRIPTION
**Pull request by luyseyal**
If you like this approach to autoComplete=polite, I can push up some documentation and a test for it.

### CODE REVIEW

**Comment by jackocnr** [comment]
Thank you so much for jumping on this.

Can we can do this without a new initialisation option? Can we literally just check if there is already an autocomplete attribute on the input, and only add `autocomplete=off` if not?

**Comment by luyseyal** [comment]
@jackocnr I was worried that intl-tel-input might be used as a bolt-on to a framework which defaults to adding autocompletes and you might end up with mysterious "why doesn't the flag match in Drupal/Sugar/whatever?" bugs... especially when it might depend on browser load order.

Is that valid? Or overthinking it? I don't have an example or anything...

**Comment by jackocnr** [comment]
Hmm it's a good thought, but it's not an issue I've heard of yet, and I'd really rather avoid adding any more initialisation options until we really have to. Thanks.

**Comment by luyseyal** [comment]
Updated PR. Checking element and its form for extant autocomplete before setting it to off.

**Comment by jackocnr** [comment]
Manually merged, thank you! This will be in the next release.

**Pull request closed without merging**
