### PR TITLE
Don't mutate arrays passed in options

### PR DESCRIPTION
**Pull request by tinovyatkin**
You are lowercasing values of arrays passed in options - it’s not something expected by developers, nor it's documented anywhere. This PR fixes that and also uses native array methods in favour of JQuery (taking in account IE9+)

### CODE REVIEW

**Comment by jackocnr** [comment]
Hi Tino, thanks for submitting this. I'm sorry this has taken me so long to review - I'm getting ready to move my family to another country soon!

Did you test this change? I just checked it out and built the js, and we have loads of test failures. Also I tried it out manually (by initialising the plugin with `onlyCountries: ['gb']` and it didn't work).

**Comment by tinovyatkin** [comment]
Hi @jackocnr! `npm test` show no failures for me and I was thinking this part is covered by `intl-tel-input/src/spec/tests/options/excludeCountries.js` and `intl-tel-input/src/spec/tests/options/onlyCountries.js` - doesn't it?

**Comment by jackocnr** [comment]
As per https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md you need to build the JS files and commit them as well. Travis just runs the tests against build/js/intlTelInput.min.js

**Comment by tinovyatkin** [comment]
I'm sorry, was confused by tests... Fixed now.

**Comment by jackocnr** [comment]
I rebased these commits and merged in the command line. Thank you so much @tinovyatkin!

**Pull request closed without merging**
