### PR TITLE
Fix “ReferenceError: window is not defined” when importing code in Node.js

### PR DESCRIPTION
**Pull request by jacksonrayhamilton**
I had a problem similar to #707.

I have some JS files that are glued together with Webpack, which looks at the ES6 `import` syntax I use to determine which files to bundle up.  This means I am loading intl-tel-input in both my Node.js server code and my browser code.  My Node.js server code is going to render some HTML using another library but skip calling `intlTelInput()` on the server.  Then when the code is loaded in the browser `intlTelInput()` will enhance my input.

The problem is that if I so much as add `import intlTelInput from 'intl-tel-input'` to my server code, I get an error: `ReferenceError: window is not defined`.

I could dynamically import my dependency with `await import('intl-tel-input')` to avoid the ReferenceError, but that adds complexity.  It would be much nicer if all I needed to do was `if (typeof window === 'object') intlTelInput(domNode)`.

I think that with a slight modification to the style in which we initialize the library, such that we write in a more environment-agnostic [(“isomorphic”)](https://cdb.reacttraining.com/universal-javascript-4761051b7ae9) style, this use case can be served.  I believe that f210096 achieved this.

I made the change 8301a94 in response to what you said about `windowLoaded` in this comment: https://github.com/jackocnr/intl-tel-input/issues/707#issuecomment-371783661

~I went ahead and extended the code style further in 5fbe95c to be more consistent.  If you are amenable to this broader change then the tests could probably benefit from it too.  But in case you don’t like that, we can roll it back.~  _(Whoops, that broke the tests.  Nevermind.)_

Thanks for taking your time to review this.

### CODE REVIEW

**Comment by jackocnr** [comment]
Thanks so much for this @jacksonrayhamilton, I think the "Avoid referencing..." commit is perfect and ready to merge.

As for the "Synchronously..." commit, while I appreciate that I did say that in that old thread, in this context (just importing the plugin, but not initialising) there's no point as that value wont be read at all. I think if we wanted to look into allowing you to initialise the plugin on the server, then we'd need to consider it then, but in that case there's a lot more to consider that we haven't yet. So can we remove this for now?

And finally, in the "Build changes..." commit, it seems to be injecting a typeof polyfill - any idea what is causing this to be added and why? I don't think we need this do we?

Thanks again, I look forward to getting this merged.

**Comment by jacksonrayhamilton** [comment]
> As for the "Synchronously..." commit … So can we remove this for now?

Sure, I removed it.  I also rebased on v16.0.15 and force-pushed to this branch.

> And finally, in the "Build changes..." commit, it seems to be injecting a typeof polyfill - any idea what is causing this to be added and why? I don't think we need this do we?

I imagine that Babel adds that to be extra extra safe.  ES6 added `Symbol` and extended the range of possible return values of `typeof`.  Theoretically, the code could run in ES5 _and_ the environment could have a `Symbol` polyfill _and_ the environment could assign `window = Symbol('window')` _but_ the `typeof window` operations in intlTelInput.js would incorrectly return `"object"` rather than `"symbol"` in that environment.

Highly unlikely, I know.  But is it worth configuring Babel to not do it?  Eh, I prefer to generally assume that preset-env is wiser than I am about compiling JS.  And it’s only a few extra bytes.

**Comment by jackocnr** [comment]
> Sure, I removed it. I also rebased on v16.0.15 and force-pushed to this branch.

Amazing, thanks.

> I prefer to generally assume that preset-env is wiser than I am about compiling JS. And it’s only a few extra bytes.

I totally agree in the general case, but in the case of a plugin which will be imported into other people's projects - I think it's their job to decide the Babel config that applies to all of their code.

**Comment by jacksonrayhamilton** [comment]
Alright, I disabled the `typeof` transform.

**Comment by jackocnr** [comment]
Thanks so much for this. And I think excluding the typeof transform was the right thing to do - this article discusses it, and how it's only needed if you're using typeof with Symbols: https://medium.com/@WebReflection/avoiding-babels-production-bloat-d53eea2e1cbf

**Pull request merged**
