### PR TITLE
Create composer.json copied from intl-tel-input.jquery.json

### PR DESCRIPTION
**Pull request by defro**
Hello ! 
When I want to install your fabulous plugin with composer, I need a composer.json file. So I just created this file as a copy of your file intl-tel-input.jquery.json.
If you can add this file to your project it will be marvelous.
Regards,
Joel

PS: Sorry for my english, I'm a trench guy
PS2: Have a wonderful christmas eve

### CODE REVIEW

**Comment by jackocnr** [comment]
Hi there, thanks for putting this together.

A couple of things to get this merged:

1) Fix the "name" to be this repo!
2) Add a reference in the file grunt/bump.js so the version gets automatically updated on new releases

**Comment by defro** [comment]
Many thanks for your reply and you seems to be agree to integrate my push request.
I did the changes you asked...
What do you think about ?

**Comment by jackocnr** [comment]
Thanks!

**Comment by defro** [comment]
Thanks again for the add !
Right now I can easily use your librairie as a PHP component.

For this, I added your library to packagist : https://packagist.org/packages/jackocnr/intl-tel-input
I want to add you as maintainer so you must create an account on the website.

After you will see this message : "This package is not auto-updated. Please set up the GitHub Service Hook for Packagist so that it gets updated whenever you push!" 
I think you will be able to set up the configuration after that.

**Comment by jackocnr** [comment]
Ok I have created an account.

**Comment by defro** [comment]
Nice ! I just added you. I hope you can see this message : "This package is not auto-updated. Please set up the GitHub Service Hook for Packagist so that it gets updated whenever you push!"

**Comment by jackocnr** [comment]
Ok I've setup the webhook, and the message has gone 👍

**Comment by defro** [comment]
Perfect ! You rock

**Pull request merged**
