### PR TITLE
Fix issue 1089

### PR DESCRIPTION
**Pull request by tomas-nz**
Don't replace area codes of NANP numbers when changing country code.

### CODE REVIEW

**Comment by jackocnr** [comment]
Thanks for this. It's saying there are conflicts - would you be able to resolve those? And ideally squash commits into a single one.

**Comment by tomas-nz** [comment]
@jackocnr I managed to squash the commits. The message above here on the PR says "This branch has _no conflicts_ with the base branch" and has a green tick. If I missed something, kindly point me in the right direction.

**Comment by jackocnr** [comment]
That seems to have fixed the conflict issue, thanks.

**Comment by jackocnr** [comment]
Thanks for this PR. I agree with your conclusion that it's best not to touch any area codes when changing flags, for consistency.

Unfortunately this solution only fixed the issue for NANP countries, but not for other countries where we handle dial codes e.g. +61. I've now pushed a more comprehensive fix to master, so I'll close this. Thanks for your help driving this forwards.

**Pull request closed without merging**
