### PR TITLE
Tweak Jasmine config to use custom browser on MacOSX (arm64)

### PR DESCRIPTION
**Pull request by oleh-demyanyuk**

### CODE REVIEW

**Comment by jackocnr** [comment]
Hi there, can you provide some information on why this is needed?

**Comment by oleh-demyanyuk** [comment]
Hi @jackocnr 
I've had troubles running `npm test` on MacOSX with recent `chromedriver` (installed via `brew`).
Currently new popular way is to use `Google Chrome for Testing`
https://developer.chrome.com/blog/chrome-for-testing

So I've tweaked config to be able to run against `Google Chrome for Testing` .
After test passed I was able to build lib on MacOSX and integrate into rails related lib.
You can ignore it, or rewrite as you see it.
Regards

**Comment by carlssonemil** [comment]
For anyone coming here having the same problems as @oleh-demyanyuk above, this is how I got it working on my M1 MacBook:
1. Follow the steps in [this guide](https://luisrangelc.medium.com/resolving-the-chromium-binary-not-available-for-arm64-error-during-puppeteer-installation-on-12d02402f619) to get Chromium installed on your machine
2. Manually override the hardcoded path to Chromium (🤦) in the `Launcher.js` file in `node_modules/puppeteer` (more detailed info can be found in [this comment](https://github.com/puppeteer/puppeteer/issues/5662#issuecomment-891297815))

The environmental variables you set in your `~/.zshrc` to define where Chromium is installed doesn't work for some reason. And I'm guessing you have to manually change this if you run `npm install` again after this.

**Comment by iflows-robert** [comment]
hy jackocnr, how did you resolved issues/1289?

**Comment by jackocnr** [comment]
We're now [moving over to Jest](https://github.com/jackocnr/intl-tel-input/issues/1630), so I'll close this.

**Pull request closed without merging**
