### PR TITLE
Country search option

### LINKED ISSUE #1461: Live searching need add
### Steps to reproduce
1.  live search not working
### Expected behaviour
A country name search option is needed.
is it possible to add a search option?

### Actual behaviour
Country name search option not found.

### Initialisation options
List any options you're using e.g. utilsScript or preferred countries

### PR DESCRIPTION
**Pull request by packiyarajpatchath**
Fix #1461 Live searching need add, Able to search with country name and dial code.

### CODE REVIEW

**Comment by vadivelar** [comment]
Is there any plan to merge this PR?  we also need option. @jackocnr

**Comment by jackocnr** [comment]
You can already search the country names just by opening the dropdown and typing the first couple of letters. I'm reluctant to add a 2nd input into the mix (in addition to the main phone number input) as I think it makes the UX much more complex/confusing. With that said, I will keep an open mind and will happily review this PR when I next have some free time - most likely in December.

**Comment by jackocnr** [comment]
Screenshot 2023-12-07 at 13 57 37

Adding a screenshot for reference.

Apologies for the delay in reviewing this properly.

Thanks for putting this together. I am actually coming around to the idea, but we will need a lot of changes for this to be merged. Basically, I think it should work the way [Stripe](https://dashboard.stripe.com/settings/user) do it (you need to register for an account first, then go to edit profile page, and click "add authentication method" to see their phone input):

Screenshot 2023-12-07 at 14 38 23

So the main change is that when you type, it should filter the countries to only show the ones that match what was typed. And obviously we need to make the search input fit the width of the dropdown (and we shouldn't have an `input` inside a `ul` element). And I see you've only modified the build files, but you'll need to modify the src files and then run `npm run build:js`

**Comment by apangr** [comment]
It's good to know that you are working on this functionality, I hope it is available soon, I need it :+1:

**Review by csyndicate — APPROVED** [review]

**Comment by csyndicate** [comment]
working

**Comment by jackocnr** [comment]
I've implemented this myself now. See new option `countrySearch` in v18.5.1. Let me know what you think!

**Pull request closed without merging**
