### PR TITLE
Fix typo in destroy method that causes popup to not close on destroy.

### PR DESCRIPTION
**Pull request by JvJefke**
This PR contains a simple typo in the code that causes the destroy method not to close the dropdown.

### CODE REVIEW

**Comment by jackocnr** [comment]
Good spot, thanks! If you can remove the other (non-JavaScript) changes from your commit then I'll be happy to merge.

**Comment by jackocnr** [comment]
Could we also get rid of that package-lock.json change, and squash the commits into one please?

**Comment by JvJefke** [comment]
done

**Comment by JvJefke** [comment]
It might be handy for you guys to write all this down in the contribution guide. Otherwise you'll have to ask this stuff everytime.

**Comment by jackocnr** [comment]
Thank you so much!

**Pull request merged**
