### PR TITLE
isValidNumber now returns null value when utils script is not available

### LINKED ISSUE #362: isValidNumber assumes that number is invalid
Hello!

The `isValidNumber` API method uses `intlTelInputUtils.isValidNumber` function to actually validate the phone number. However, when `utils.js` is not loaded, it [assumes that number is incorrect](https://github.com/jackocnr/intl-tel-input/blob/master/src/js/intlTelInput.js.ejs#L1070).

I think that library shouldn't make such assumptions without any base. So in case when `utils.js` is not available it should fallback to some other internal validation method, e.g. simple RegExp or just return `null` instead of `false`.

I believe that `null` is more correct result when you can't came up with the actual result.

What do you think? Thank you.

### PR DESCRIPTION
**Pull request by slavafomin**
Fixes #362.

### CODE REVIEW

**Comment by jackocnr** [comment]
Thanks!

**Comment by slavafomin** [comment]
My pleasure. Will you be able to release this change in the new version soon?

**Comment by jackocnr** [comment]
Actually v8.0.1. Done.

**Comment by slavafomin** [comment]
Oh, I would really want to use `autoFormat` feature. This is probably the most important thing in the whole library for us. It works pretty great with international phone numbers in our locality. Are you planning to completely drop support for this feature?

I'm going to stick with the `7.x` branch for now then. Could you please merge this change into this branch as well?

**Comment by jackocnr** [comment]
I feel your pain, but unfortunately I had to remove `autoFormat` because it is fundamentally broken for 49 countries including USA. See a full list here: https://github.com/jackocnr/intl-tel-input/issues/346#issuecomment-183771143. If you want your site to work for people from those countries, then you shouldn't use `autoFormat`.

If you still choose to, you can continue to use v7 of the plugin, but I will not be maintaining it.

**Pull request merged**
