### PR TITLE
Add selected country on trigger change

### PR DESCRIPTION
**Pull request by JensDebergh**
It feels strange to have a custom `countrychange` event without returning the newly selected country in the callback. 

Before:
```
var $input = $('#phone);

$input.intlInput({});

$input.on('countrychange', function(e) {
    var country = $input.intlTelInput("getSelectedCountryData");
    // Do something with country object
});
```

Now:
```
var $input = $('#phone);

$input.intlInput({});

// Get country object without using static methods
$input.on('countrychange', function(e, country) {
  // Do something with country object
});
```

Kind Regards

### CODE REVIEW

**Comment by jackocnr** [comment]
Yea this makes sense, thank you. And thanks for adding a test for it, great work.

Two small things before I merge:
1) You have removed all the trailing whitespace from the readme which has broken the markdown formatting - please undo this
2) This change shouldn't affect the flag images, so please remove those changes from the pull request

Thanks again :)

**Comment by jackocnr** [comment]
Hmm unfortunately I'm still seeing the image changes.

**Comment by JensDebergh** [comment]
I'm sorry, I've accidently squashed those commits so I can't revert them. I've done what the guidelines told me and this was to run `grunt build`, which in turn compiles the `flags` asset.

**Comment by jackocnr** [comment]
Merged, thank you!

**Pull request merged**
