### PR TITLE
1415  and 1419 screen reader enhancements

### PR DESCRIPTION
**Pull request by danman01**
1419 - fixes screen reader not reading select box option

closes https://github.com/jackocnr/intl-tel-input/issues/1419

1415: remove duplicate country code from screen reader

closes https://github.com/jackocnr/intl-tel-input/issues/1415

### CODE REVIEW

**Comment by jackocnr** [comment]
Thanks so much for putting this together @danman01.

My only feedback is that when separateDialCode is disabled, we still want to include the dial code in the title.

**Comment by danman01** [comment]
@jackocnr Updated! Let me know if you think the specs are in the right place? After working on it, it looks like the "Unknown" title scenario won't ever get hit, but there might be some case where we still need it in there.

**Comment by jackocnr** [comment]
This looks really great, thank you! Any chance you could build the JS as well? Then we can merge.

https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#changes-to-the-plugin

**Comment by danman01** [comment]
@jackocnr I ran the build js command and committed the results

**Comment by jackocnr** [comment]
Thanks again

**Pull request merged**
