### PR TITLE
removed certain jQuery dependencies

### PR DESCRIPTION
**Pull request by DidierLmn**
I've seen you are trying to move away from jQuery ([#405](https://github.com/jackocnr/intl-tel-input/issues/405)),  and thus I've tried to contribute towards this end.

One of the things I've done is replace `$.ajax` with a `XMLHttpRequest`, however the tests will flag this as issues since they check for `$.ajax.calls`. I've never worked with these tests so I'm uncertain how to adapt/correct these, maybe someone else knows/can help?

Thanks

### CODE REVIEW

**Comment by jackocnr** [comment]
Hi there, thanks for putting this together, but I think [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) is the new standard way to do this. There is actually a note about this in the wiki page, which is linked from that issue you mentioned.

**Comment by sheyooo** [comment]
But no IE browser has `fetch` support

**Comment by jackocnr** [comment]
No, that would require a polyfill, which I'm sure a lot of sites are already using.

**Comment by sheyooo** [comment]
I would have loved to help but, I don't know my way around

**Comment by DidierLmn** [comment]
Thanks for the feedback, I overlooked the wiki. I will look it over and try to make another pull request.

**Pull request closed without merging**
