### PR TITLE
Add custom class option

### PR DESCRIPTION
**Pull request by subversivo58**
Possibily add custom class to container element.

Reference discussion based from this issue: #675

### CODE REVIEW

**Comment by jackocnr** [comment]
Thanks for this! Please could you update the default value to be an empty string, to match the other string based options. And also please can you combine all of these commits into one. Thanks.

**Comment by subversivo58** [comment]
Yes, I think I can do it soon.

**Comment by chtheis** [comment]
I'm looking for exactly this, but I can't find it in the code. Am I missing something?

**Comment by jackocnr** [comment]
I don't think this was ever finished. It would actually be very easy to just do this manually, after you initialise the plugin, either grab the input's parent element, or just select the element with the class `intl-tel-input` and add your class manually.

**Comment by chtheis** [comment]
Am 12.01.2019 um 17:39 schrieb jackocnr:
> I don't think this was ever finished. It would actually be very easy to 
> just do this manually, after you initialise the plugin, either grab the 
> input's parent element, or just select the element with the class 
> |intl-tel-input| and add your class manually.

I can create a patch for it, based on previous work. I don't like to 
manipulate the elements manually ...

I guess the dist/* files are created by some build process and I have to 
patch src/*? The original PR changed the dist/* files which felt strange.

**Comment by jackocnr** [comment]
See the Contributing wiki page for more info: https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#changes-to-the-plugin

**Comment by chtheis** [comment]
Am 12.01.2019 um 19:06 schrieb jackocnr:
> See the Contributing wiki page for more info: 
> https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#changes-to-the-plugin

OK, I created the PR. I named the parameter "customParentClass" instead 
of what was in the original PR

npm builds the .js-files without complains.
I did not add a test case: the scripts are beyond me :) And "npm test" 
fails, possibly because it couldn't launch chrome.

**Pull request closed without merging**
