### PR TITLE
Update data.js

### PR DESCRIPTION
**Pull request by jyotsnagaddam**
Showing Russian flag for Kazakhstan number (#912)
Added area codes for countries that share same international dial codes.
1. Western Sahara, +212
2. Mayotte, +262
3. Aland Islands, +358
4. Vatican City, +39
5. Guernsey, +44
6. Isle of Man, +44
7. Jersey, +44
8. Svalbard and Jan Mayen, +47
9. Caribbean Netherlands, +599
10. Kazakhstan, +7

### CODE REVIEW

**Comment by jackocnr** [comment]
This looks perfect, thank you very much.

Please could you try [building the JS](https://github.com/jackocnr/intl-tel-input/blob/master/.github/CONTRIBUTING.md#changes-to-the-plugin) and check that everything is still working, and that the tests still pass?

**Comment by jackocnr** [comment]
I've just checked and the tests pass, and everything seems to be working, but just one issue: we need to update this line as the max dial code length has now grown from 4 to 7: https://github.com/jackocnr/intl-tel-input/blob/master/src/js/intlTelInput.js#L1106

**Comment by jyotsnagaddam** [comment]
Yes auto-generation is a right way to address the issue. I did the changes as proposed. I just tested on my local copy and changes are looking fine. Please validate.

**Comment by jyotsnagaddam** [comment]
I have a question regarding 'separatedialcode' option. It seems only for NANP countries who have single area code will have the dialcode as +1 followed by area code. For other countries like US and CA dialcode will show as '+1'

But for all other countries that share same international dialing code, we are not showing the area code followed by country code even if the country has single area code when we set the 'seperatedialcode'.

Is my understanding correct?

**Comment by jackocnr** [comment]
> I did the changes as proposed. I just tested on my local copy and changes are looking fine. Please validate.

Did you push the changes? I'm not seeing them in this PR.

> I have a question regarding 'separatedialcode' option. It seems only for NANP countries who have single area code will have the dialcode as +1 followed by area code. For other countries like US and CA dialcode will show as '+1'

> But for all other countries that share same international dialing code, we are not showing the area code followed by country code even if the country has single area code when we set the 'seperatedialcode'.

> Is my understanding correct?

Yes that is correct. Currently for some NANP countries we include the area code in the dial code field in data.js, e.g. [+1242 for Bahamas](https://github.com/jackocnr/intl-tel-input/blob/master/src/js/data.js#L92). Now that I think about this, I think it would be better to keep the area codes separate even in cases where there is only one, because even in those cases, the official international dial code is still just +1. But I think don't worry about that in this PR - I think we can refactor those ones in another PR. Cheers.

**Comment by jyotsnagaddam** [comment]
My bad, I thought I created the pull request yesterday itself. It seems, I just saw the preview changes and forgot submitting the pull request. I just did it, can you please check?

**Comment by jyotsnagaddam** [comment]
> > I did the changes as proposed. I just tested on my local copy and changes are looking fine. Please validate.
> 
> Did you push the changes? I'm not seeing them in this PR.
> 
> > I have a question regarding 'separatedialcode' option. It seems only for NANP countries who have single area code will have the dialcode as +1 followed by area code. For other countries like US and CA dialcode will show as '+1'
> 
> > But for all other countries that share same international dialing code, we are not showing the area code followed by country code even if the country has single area code when we set the 'seperatedialcode'.
> 
> > Is my understanding correct?
> 
> Yes that is correct. Currently for some NANP countries we include the area code in the dial code field in data.js, e.g. [+1242 for Bahamas](https://github.com/jackocnr/intl-tel-input/blob/master/src/js/data.js#L92). Now that I think about this, I think it would be better to keep the area codes separate even in cases where there is only one, because even in those cases, the official international dial code is still just +1. But I think don't worry about that in this PR - I think we can refactor those ones in another PR. Cheers.

Got it. Thanks.

**Comment by jackocnr** [comment]
Thanks so much for your help here 👍

**Pull request merged**
