### PR TITLE
fixed the bug for iti__country overlapping the screen on mobile view …

### PR DESCRIPTION
**Pull request by timothy-okoduwa**
fixed the bug for iti__country overlapping the screen on mobile view . And also iti__country-list adding a border-radius to make it more stylish

### CODE REVIEW

**Comment by jackocnr** [comment]
Hi there, please can you give more information about the overlap issue? Maybe provide a codepen or something so I can reproduce it?

**Comment by timothy-okoduwa** [comment]
Hi jackocnr, its so wonderful to hear from you. So this is what i spotted out when i used intl-tel-input for a project, upoon going to a mobile screen i spotted out that the country drop down was over lapping the screen making it wiggly

Screen Shot 2023-08-17 at 9 29 36 AM

so i made some changes (if you dont mind) to the css to make it fit on mobile and this is my out come

Screen Shot 2023-08-17 at 9 47 23 AM

this is a link to the page where i used it (the one i fixed) although sometimes the css and the orignal css conflicts thats why i used the  "!important" in my css styles i added so you may see some little conflict when the page tries to load up, but it works fine. https://hair-master.vercel.app/billing.html
i will really like to hear back from you. Thanks so much for giving me an audience.

**Comment by timothy-okoduwa** [comment]
Hi jackocnr, its so wonderful to hear from you. So this is what i spotted out when i used intl-tel-input for a project, upoon going to a mobile screen i spotted out that the country drop down was over lapping the screen making it wiggly

Screen Shot 2023-08-17 at 9 29 36 AM

so i made some changes (if you dont mind) to the css to make it fit on mobile and this is my out come

Screen Shot 2023-08-17 at 9 47 23 AM

this is a link to the page where i used it (the one i fixed) although sometimes the css and the orignal css conflicts thats why i used the  "!important" in my css styles i added so you may see some abnormalies

**Comment by jackocnr** [comment]
Thanks for explaining the issue. I haven't come across this before. If you can find the minimal set of code that reproduces the problem and put that in a CodePen, then I'd be happy to take a look. Here is [an example pen](https://codepen.io/jackocnr/pen/yehvE) with the plugin up and running - feel free to fork this if it helps.

**Comment by ighorbani** [comment]
Hi 
I have the same issue. let me explain you. if you in that code pen come to mobile view and then refresh the page you could see the problem.
options starts from the top of page not below that input.
image

**Comment by jackocnr** [comment]
I'm confused. Let's take the [demo page](https://intl-tel-input.com/) - if I open Chrome dev tools, open the device toolbar, and select "Pixel 5", refresh the page, and open the dropdown, I get the following. Is this not what you see? What device/OS/version are you on?

Screenshot 2023-08-20 at 11 00 43

**Comment by jackocnr** [comment]
Looking at this again, @timothy-okoduwa I think your issue is just some sort of clash with your own website CSS, which you should fix in your own code - either with overrides, or with some sort of re-structuring so your styles are not affecting the plugin's elements. I don't think we need to make changes to the core plugin for this.

@ighorbani I think you've just got chrome devtools set to responsive mode, so you can make the viewport smaller, but you're not actually selecting a mobile phone from the dropdown, so it's still sending a desktop userAgent string, so the plugin still shows the country list as a dropdown instead of a fullscreen popup. This is currently working as intended, although we are exploring an alternative in [this PR](https://github.com/jackocnr/intl-tel-input/pull/1463) if you're interested, which would give you more control over when to show the fullscreen popup or not.

Let me know if I've misunderstood something, otherwise I will close this PR. Thanks.

**Pull request closed without merging**
