### PR TITLE
Update libphonenumber to v8.12.18

### PR DESCRIPTION
**Pull request by OsaAjani**
This pull request update src/utils.js to use libphonenumber v8.12.18 (including among other things transition from 8 to 10 chars phone numbers for Ivory Coast #1189). #1198

### CODE REVIEW

**Comment by Bartlebyy** [comment]
While the minified version might be faster, it also makes that file completely unreadable and uneditable going forward. I'd rather the compiler minify the file and leave this file readable

**Review by Bartlebyy — CHANGES_REQUESTED** [review]
@OsaAjani While the minified version might be faster, it also makes that file completely unreadable and uneditable going forward. I'd rather the compiler minify the file and leave this file readable

**Comment by OsaAjani** [comment]
Absolutly, my mistake i havent realized the file have been minified in the building process. I will have to find where in the process the file is minified and how to disable it.

**Comment by OsaAjani** [comment]
My bad, i've been copying the minified version in `src` instead of `build`. So i basicly copied back the old utils.js in src, add the namespace without with i cannot compile the script, and add the minified version to build dir.

**Comment by jonathan42** [comment]
#1213

**Comment by jackocnr** [comment]
Thanks so much for putting this together, and apologies for my delay in reviewing - I've been dealing with a family emergency. I've just bumped us up to v8.12.21, so I'll close this one now. Thanks again.

**Pull request closed without merging**
