### PR TITLE
ci: test Node.js 8, 10 and 11

### PR DESCRIPTION
**Pull request by DanielRuf**
Test the current LTS branches too. See https://github.com/nodejs/Release/blob/master/README.md

### CODE REVIEW

**Comment by DanielRuf** [comment]
Only Node.js >= 8 is supported which we should make clear in the `engines` field in package.json.

https://travis-ci.org/jackocnr/intl-tel-input/builds/451258484

**Comment by jackocnr** [comment]
Thanks!

**Comment by DanielRuf** [comment]
> Only Node.js >= 8 is supported which we should make clear in the `engines` field in package.json.

Should I create a separate PR for this?

**Comment by jackocnr** [comment]
That would be great, thank you.

**Pull request merged**
